version: '3'

services:
  db:
    image: postgres:9.6.5-alpine
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: ./EternalRSSAPI
      dockerfile: $PWD/EternalRSSAPI/Dockerfile.dev
    env_file:
      - ./EternalRSSAPI/server.env
    volumes:
      - $PWD/EternalRSSAPI
    ports:
      - 5000:80
    depends_on:
      - db

volumes:
  pgdata:
